---
title: "DES for Methods and Techniques"
author: "Becca Scully"
date: "5/13/2022"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(kableExtra)
library(tidyverse)
library(sjPlot)

```
Be sure to run code to double check that the DES tables are updated to the MetadataDict.csv (wrote code here to run this fucntion )


```{r}
tablesDES <- c("RecordLevel", "Location", "Event", "MeasurementOrFact")
file_path <- str_remove(getwd(), "/Tables For Manuscripts") 


rawTable <- read.csv(paste0(file_path, "/", tablesDES[1], "DES.csv")) 
DESTable <- rawTable %>% 
                    select(c(term,termID, definition, dataType, examples, noteAndConventions))
kable(DESTable, row.names=FALSE, aline = c)  %>% 
   kable_styling(latex_options = "striped", font_size = 9) 
 
rawTable <- read.csv(paste0(file_path, "/", tablesDES[2], "DES.csv")) 
DESTable <- rawTable %>% 
                    select(c(term,termID, definition, dataType, examples, noteAndConventions))

 kable(DESTable, row.names=FALSE, aline = c)  %>% 
   kable_styling(latex_options = "striped", font_size = 9) 
 
rawTable <- read.csv(paste0(file_path, "/", tablesDES[3], "DES.csv")) 
DESTable <- rawTable %>% 
                    select(c(term,termID, definition, dataType, examples, noteAndConventions))

 kable(DESTable, row.names=FALSE, aline = c)  %>% 
   kable_styling(latex_options = "striped", font_size = 9) 
 
rawTable <- read.csv(paste0(file_path, "/", tablesDES[4], "DES.csv")) 
DESTable <- rawTable %>% 
                    select(c(term,termID, definition, dataType, examples, noteAndConventions))

 kable(DESTable, row.names=FALSE, aline = c)  %>% 
   kable_styling(latex_options = "striped", font_size = 9) 
 
 
```
```{r}

file_path <- str_remove(getwd(), "/Tables For Manuscripts") 
cv <- read.csv(paste0(file_path, "/metricControlledVocabulary.csv"))

cv<- cv %>% 
      select(c(measurementTypeID, measurementType, description, units, dataType, minimumPossibleValue, maximumPossibleValue))

 kable(cv, row.names=FALSE, aline = c)  %>% 
   kable_styling(latex_options = "striped", font_size = 9) 

```

```{r}


```



