---
title: "Appendix A"
author: "Becca Scully"
date: "5/16/2022"
output:
  html_document: default
---

```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)

library(knitr)
library(kableExtra)
library(tidyverse)

library(pander)

file_path <- str_remove(getwd(), "/Tables For Manuscripts") 
mapping <- read.csv(paste0(file_path, "/DataMapping.csv")) 
cv <- read.csv(paste0(file_path, "/metricControlledVocabulary.csv"))

#mapping <- read.csv(paste0(getwd(), "/DataMapping.csv")) 
#cv <- read.csv(paste0(getwd(), "/metricControlledVocabulary.csv"))

dataTables <- function(ID) {

  metricCV <- cv %>% 
          filter(measurementTypeID ==  ID ) %>% 
          select(-c(termID, term, entity,dataType, sourcedefinition, attribute, title))

kbl(metricCV, row.names=FALSE) %>% 
   kable_styling(latex_options = "striped", font_size = 9) 

 

} 

dataTablesMapping <- function(ID) {
  
metricMap <- mapping %>% 
        filter(measurementTypeID ==  ID) %>% 
        dplyr::select(-c(measurementTypeID, measurementType, termID, term, dataType))
  
kbl(metricMap, row.names=FALSE) %>% 
   kable_styling(latex_options = "striped", font_size = 9) 

    }


```


```{r}
dataTables(504)
dataTablesMapping(504)
```

```{r}
dataTables(506)
dataTablesMapping(506)
```

```{r}
dataTables(508)
dataTablesMapping(508)
```

```{r}
dataTables(502)
dataTablesMapping(502)
```

```{r}
dataTables(503)
dataTablesMapping(503)
```

```{r}
dataTables(509)
dataTablesMapping(509)
```

```{r}
dataTables(511)
dataTablesMapping(511)
```

```{r}
dataTables(510)
dataTablesMapping(510)
```

```{r}
dataTables(514)
dataTablesMapping(514)


dataTables(515)
dataTablesMapping(515)


dataTables(516)
dataTablesMapping(516)


dataTables(517)
dataTablesMapping(517)

dataTables(518)
dataTablesMapping(518)

dataTables(519)
dataTablesMapping(519)

```

```{r}
dataTables(520)
dataTablesMapping(520)

dataTables(522)
dataTablesMapping(522)
```

```{r}
dataTables(523)
dataTablesMapping(523)

dataTables(524)
dataTablesMapping(524)

dataTables(525)
dataTablesMapping(525)

dataTables(526)
dataTablesMapping(526)

dataTables(527)
dataTablesMapping(527)

dataTables(528)
dataTablesMapping(528)

```